import pandas as pd
import matplotlib.pyplot as plt
dataset = pd.read_csv("dataset.csv")
plt.xlabel("nm, data from PIA25", fontsize=8, fontweight="bold")
#plt.ylabel("Ось Y\nЗависимая величина", fontsize=8, fontweight="bold")
z = (dataset[" Elapsed"])
plt.title('Beamage data analysis')
plt.plot(dataset["Date"],dataset[" Elapsed"],dataset[" dSigma X(um)"],label="dSigma X(um)")# ,'b' # blue markers with default shape 'ro' # red circles 'g-', '--' 
plt.legend()
plt.plot(dataset["Date"],dataset[" dSigma Y (um)"],label="dSigma Y (um)")
plt.legend()
plt.plot(dataset["Date"],dataset[" dSigma X(um)"], label="dSigma X(um)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Ellipticity(%)"],label="Ellipticity(%)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Centroid X(um)"],label="Centroid X(um)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Centroid y(um)"],label="Centroid y(um")
plt.legend()
plt.plot(dataset["Date"],dataset[" Peak X(um)"],label="Peak X(um)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Peak Y(um)"],label="Peak Y(um)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Peak Saturation level(%)"],label="Peak Saturation level(%)")
plt.legend()
plt.plot(dataset["Date"],dataset[" Peak to Average Ratio X"],label="Peak to Average Ratio X")
plt.legend()
plt.plot(dataset["Date"],dataset[" Peak to Average Ratio Y"],label="Peak to Average Ratio Y")
plt.legend()
plt.plot(dataset["Date"],dataset[" Delta Centroid X"],label="Delta Centroid X")
plt.legend()
plt.plot(dataset["Date"],dataset[" Delta Centroid Y"],label="Delta Centroid Y")
plt.legend()
plt.plot(dataset["Date"],dataset[" Delta Peak X"],label="Delta Peak X")
plt.legend()
plt.plot(dataset["Date"],dataset[" Delta Peak Y"],label="Delta Peak Y")
plt.legend()
plt.show()


  
